#######
steps:
  # Step 1: Install dependencies and build the React app
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build

  # Step 2: Upload the contents of the "build" folder (not the folder itself) to the GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', './build/*', 'gs://$_BUCKET_NAME']

  # Step 3: Set Cache-Control headers (disable caching for fast updates)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'setmeta', '-h', 'Cache-Control:no-cache, max-age=0', 'gs://$_BUCKET_NAME/**']

  # Step 4: Invalidate Cloud CDN cache to reflect changes immediately
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute url-maps invalidate-cdn-cache $_URL_MAP_NAME --path "/*" --async || echo "Cache invalidation failed."

substitutions:
  _BUCKET_NAME: 'reacttestcicd'
  _URL_MAP_NAME: 'cdnreactlb'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'
